dist: xenial

language: cpp
sudo: false
compiler: clang

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -Bbuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -Wdev
  - cd build

script:
  - make -j 2
  - ctest -V -j 2